"""
Configuration package for centralized constants and settings
"""

from .constants import (
    FREE_TRIAL_WORK_COUNT,
    DEFAULT_TRIAL_DAYS,
    MAX_LOGIN_ATTEMPTS,
    LOGIN_ATTEMPT_WINDOW_MINUTES,
    MAX_IP_ATTEMPTS,
    MIN_PASSWORD_LENGTH,
    BCRYPT_ROUNDS,
    SESSION_EXPIRY_DAYS,
    JWT_EXPIRY_HOURS,
    ADMIN_REFRESH_INTERVAL_MS,
    ADMIN_PAGE_SIZE_DEFAULT,
    ADMIN_PAGE_SIZE_MAX,
    REGISTRATION_RATE_LIMIT,
    ADMIN_LIST_RATE_LIMIT,
    ADMIN_ACTION_RATE_LIMIT,
)

__all__ = [
    "FREE_TRIAL_WORK_COUNT",
    "DEFAULT_TRIAL_DAYS",
    "MAX_LOGIN_ATTEMPTS",
    "LOGIN_ATTEMPT_WINDOW_MINUTES",
    "MAX_IP_ATTEMPTS",
    "MIN_PASSWORD_LENGTH",
    "BCRYPT_ROUNDS",
    "SESSION_EXPIRY_DAYS",
    "JWT_EXPIRY_HOURS",
    "ADMIN_REFRESH_INTERVAL_MS",
    "ADMIN_PAGE_SIZE_DEFAULT",
    "ADMIN_PAGE_SIZE_MAX",
    "REGISTRATION_RATE_LIMIT",
    "ADMIN_LIST_RATE_LIMIT",
    "ADMIN_ACTION_RATE_LIMIT",
]
