"""
Application constants shared across backend modules.
"""

# Trial / registration policy
EARLY_BIRD_WORK_COUNT = 5
FREE_TRIAL_WORK_COUNT = 5
DEFAULT_TRIAL_WORK_COUNT = FREE_TRIAL_WORK_COUNT
DEFAULT_TRIAL_DAYS = 365

# Security settings
MAX_LOGIN_ATTEMPTS = 5
LOGIN_ATTEMPT_WINDOW_MINUTES = 15
MAX_IP_ATTEMPTS = 10

# Password policy
MIN_PASSWORD_LENGTH = 8
BCRYPT_ROUNDS = 12

# Session settings
SESSION_EXPIRY_DAYS = 30
JWT_EXPIRY_HOURS = 24

# Admin dashboard
ADMIN_REFRESH_INTERVAL_MS = 60000
ADMIN_PAGE_SIZE_DEFAULT = 50
ADMIN_PAGE_SIZE_MAX = 100

# Rate limiting
REGISTRATION_RATE_LIMIT = "5/hour"
ADMIN_LIST_RATE_LIMIT = "600/hour"
ADMIN_ACTION_RATE_LIMIT = "300/hour"
