from __future__ import annotations

from typing import Dict, List

VOICE_PROFILES: List[Dict[str, str]] = [
    # === 여성 음성 ===
    {
        "id": "aurora",
        "label": "소희",
        "description": "맑고 밝은 톤, 생동감 있는 내레이션",
        "voice_name": "Aoede",
        "gender": "female",
        "sample_text": "반갑습니다. 저는 소희예요. 맑고 밝은 목소리로 여러분께 즐거운 이야기를 전해드리고 싶어요. 언제나 활기차고 긍정적인 에너지를 담아 말씀드릴게요.",
    },
    {
        "id": "luna",
        "label": "지현",
        "description": "차분하고 부드러운 내레이션",
        "voice_name": "Callirrhoe",
        "gender": "female",
        "sample_text": "안녕하세요. 지현이라고 해요. 차분하고 편안한 목소리로 여러분의 이야기를 함께 나누고 싶습니다. 부드럽고 안정적인 톤으로 귀에 쏙쏙 들어오는 내레이션을 선사할게요.",
    },
    {
        "id": "breeze",
        "label": "예린",
        "description": "산뜻하고 경쾌한 톤",
        "voice_name": "Zephyr",
        "gender": "female",
        "sample_text": "안녕하세요. 예린이에요. 상쾌한 바람처럼 산뜻하고 경쾌한 목소리로 여러분과 함께하고 싶어요. 밝고 감성적인 분위기로 마음을 전달해 드릴게요.",
    },
    {
        "id": "crystal",
        "label": "다은",
        "description": "맑고 또렷한 발음",
        "voice_name": "Pulcherrima",
        "gender": "female",
        "sample_text": "반갑습니다. 다은이예요. 맑고 투명한 목소리로 또렷하게 말씀드릴게요. 깨끗하고 선명한 발음으로 듣기 편한 내용을 전해드리겠습니다.",
    },
    {
        "id": "stella",
        "label": "나윤",
        "description": "따뜻하고 온화한 톤",
        "voice_name": "Laomedeia",
        "gender": "female",
        "sample_text": "안녕하세요. 나윤이에요. 부드럽고 온화한 목소리로 여러분께 편안함을 드리고 싶습니다. 은은하고 따뜻한 톤으로 마음을 어루만지는 이야기를 들려드릴게요.",
    },
    {
        "id": "mira",
        "label": "미라",
        "description": "부드럽고 매끄러운 제품 소개 톤",
        "voice_name": "Despina",
        "gender": "female",
        "sample_text": "안녕하세요. 미라입니다. 부드럽고 매끄러운 목소리로 제품의 매력을 자연스럽게 전해드릴게요. 쇼츠에서도 편안하게 들리는 내레이션을 만들어보겠습니다.",
    },
    {
        "id": "yuna",
        "label": "유나",
        "description": "따뜻하고 설득력 있는 쇼핑 내레이션",
        "voice_name": "Sulafat",
        "gender": "female",
        "sample_text": "반갑습니다. 유나예요. 따뜻하지만 또렷한 톤으로 중요한 포인트를 놓치지 않게 안내해드릴게요. 추천 상품의 장점을 기분 좋게 전달하겠습니다.",
    },
    {
        "id": "seoha",
        "label": "서하",
        "description": "차분하고 성숙한 신뢰감",
        "voice_name": "Vindemiatrix",
        "gender": "female",
        "sample_text": "안녕하세요. 서하입니다. 차분하고 안정적인 목소리로 필요한 정보만 깔끔하게 정리해드릴게요. 믿고 들을 수 있는 설명형 쇼츠에 잘 어울립니다.",
    },
    {
        "id": "arin",
        "label": "아린",
        "description": "젊고 또렷한 리뷰형 톤",
        "voice_name": "Leda",
        "gender": "female",
        "sample_text": "안녕하세요. 아린이에요. 밝고 젊은 분위기로 상품의 첫인상과 핵심 장점을 빠르게 알려드릴게요. 짧은 영상에서도 또렷하게 들리도록 말하겠습니다.",
    },
    {
        "id": "hayeon",
        "label": "하연",
        "description": "선명하고 전문적인 안내 톤",
        "voice_name": "Erinome",
        "gender": "female",
        "sample_text": "반갑습니다. 하연입니다. 선명한 발음과 정돈된 톤으로 제품 정보를 전문적으로 전달하겠습니다. 비교 설명이나 기능 소개 영상에 잘 어울리는 목소리입니다.",
    },
    # === 남성 음성 ===
    {
        "id": "radiant",
        "label": "도현",
        "description": "밝고 경쾌한 에너지",
        "voice_name": "Orus",
        "gender": "male",
        "sample_text": "안녕하세요. 도현입니다. 밝고 경쾌한 남성 목소리로 명확하고 힘찬 메시지를 전달해 드리겠습니다. 활기 넘치는 에너지와 함께 즐거운 이야기를 나눠볼까요.",
    },
    {
        "id": "eclipse",
        "label": "시우",
        "description": "차분하고 신뢰감 있는 톤",
        "voice_name": "Charon",
        "gender": "male",
        "sample_text": "안녕하세요. 시우입니다. 차분하고 안정감 있는 남성 목소리로 여러분께 신뢰를 드리고 싶습니다. 깊이 있는 톤으로 진중한 내레이션을 선보이겠습니다.",
    },
    {
        "id": "nebula",
        "label": "준서",
        "description": "카리스마 있고 박력있는 톤",
        "voice_name": "Fenrir",
        "gender": "male",
        "sample_text": "반갑습니다. 준서라고 합니다. 카리스마 넘치는 힘 있는 목소리로 강렬한 인상을 남기고 싶습니다. 든든하고 박력 있는 발성으로 메시지를 확실하게 전달해 드릴게요.",
    },
    {
        "id": "achird",
        "label": "민재",
        "description": "따뜻하고 포근한 톤",
        "voice_name": "Achird",
        "gender": "male",
        "sample_text": "안녕하세요. 민재예요. 따뜻하고 온화한 목소리로 여러분께 편안함을 선물하고 싶습니다. 부드러운 남성 톤으로 마음을 녹이는 이야기를 들려드릴게요.",
    },
    {
        "id": "orion",
        "label": "지호",
        "description": "활기차고 역동적인 톤",
        "voice_name": "Puck",
        "gender": "male",
        "sample_text": "안녕하세요. 지호입니다. 활기차고 생동감 넘치는 목소리로 여러분께 에너지를 전달하고 싶어요. 열정적이고 역동적인 분위기로 함께 즐거운 시간을 만들어가요.",
    },
    {
        "id": "taeoh",
        "label": "태오",
        "description": "숨결감 있는 감성 내레이션",
        "voice_name": "Enceladus",
        "gender": "male",
        "sample_text": "안녕하세요. 태오입니다. 살짝 숨결이 느껴지는 부드러운 남성 톤으로 영상의 분위기를 살려드릴게요. 감성적인 제품 소개에 잘 맞는 목소리입니다.",
    },
    {
        "id": "ian",
        "label": "이안",
        "description": "명료하고 친근한 설명 톤",
        "voice_name": "Iapetus",
        "gender": "male",
        "sample_text": "반갑습니다. 이안입니다. 명료하고 친근한 목소리로 핵심 정보를 쉽게 전달해드릴게요. 누구나 편하게 이해할 수 있는 쇼츠 내레이션을 만들겠습니다.",
    },
    {
        "id": "hyunwoo",
        "label": "현우",
        "description": "편안하고 안정적인 신뢰감",
        "voice_name": "Umbriel",
        "gender": "male",
        "sample_text": "안녕하세요. 현우입니다. 편안하고 안정적인 톤으로 제품의 장점을 차분하게 설명드릴게요. 신뢰감을 주는 추천 영상에 잘 어울립니다.",
    },
    {
        "id": "gunwoo",
        "label": "건우",
        "description": "성숙하고 깊이 있는 내레이션",
        "voice_name": "Gacrux",
        "gender": "male",
        "sample_text": "안녕하세요. 건우입니다. 성숙하고 깊이 있는 목소리로 상품 정보를 묵직하게 전달하겠습니다. 고급스러운 제품 소개나 비교 영상에 적합합니다.",
    },
    {
        "id": "jiwan",
        "label": "지완",
        "description": "지식 전달에 강한 또렷한 톤",
        "voice_name": "Sadaltager",
        "gender": "male",
        "sample_text": "반갑습니다. 지완입니다. 또렷하고 지적인 톤으로 상품의 기능과 사용 포인트를 정확하게 짚어드릴게요. 정보형 쇼츠에 잘 맞는 목소리입니다.",
    },
]

DEFAULT_MULTI_VOICE_PRESETS = [profile["voice_name"] for profile in VOICE_PROFILES[:5]]
