"""Apply manually generated Coupang Partners links from 제휴링크_입력.csv.

The Partners Open API is unavailable for this account (requires 150k+ KRW
transaction volume), so links are generated by hand on partners.coupang.com
and pasted into the CSV. This script then:

  1. Validates each pasted link (must be a link.coupang.com URL).
  2. Writes affiliate_url / result.purchase_url into the queue items.
  3. Re-arms card-less items (149/150/155/156/157/160/161) as
     linktree_retry_pending so the scheduled runner auto-creates their
     Linktree cards on the next cycle.
  4. Prints a JSON plan of existing Linktree cards whose URL must be swapped
     (handled separately via the Linktree admin session).

Usage:
    python scripts/apply_affiliate_links.py            # apply
    python scripts/apply_affiliate_links.py --dry-run  # validate only
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = REPO_ROOT / "제휴링크_입력.csv"
QUEUE_PATH = Path.home() / ".ssmaker" / "summer_coupang_autosourcing_queue_20260603.json"
REARM_NUMBERS = {"149", "150", "155", "156", "157", "160", "161"}


def load_csv() -> dict:
    links = {}
    invalid = []
    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            number = str(row.get("번호") or "").strip().zfill(3)
            link_col = next((k for k in row if k.startswith("제휴링크")), None)
            link = str(row.get(link_col) or "").strip() if link_col else ""
            if not link:
                continue
            if "link.coupang.com" not in link:
                invalid.append(f"{number}: {link[:50]}")
                continue
            links[number] = link
    if invalid:
        print(json.dumps({"error": "invalid_links", "items": invalid}, ensure_ascii=False, indent=2))
        raise SystemExit(1)
    return links


def main(argv) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    links = load_csv()
    payload = json.loads(QUEUE_PATH.read_text(encoding="utf-8-sig"))
    now = datetime.now().astimezone().isoformat(timespec="seconds")

    updated, rearmed, card_swaps = [], [], []
    for item in payload.get("items", []):
        match = re.search(r"\d+", str(item.get("planned_number") or ""))
        if not match:
            continue
        number = match.group().zfill(3)
        link = links.get(number)
        if not link:
            continue
        item["affiliate_url"] = link
        result = dict(item.get("result") or {})
        old_purchase = str(result.get("purchase_url") or "")
        result["purchase_url"] = link
        result["updated_at"] = now
        item["result"] = result
        updated.append(number)
        if number in REARM_NUMBERS:
            item["status"] = "linktree_retry_pending"
            item["attempts"] = 1  # grants one fresh Linktree-only retry
            rearmed.append(number)
        else:
            card_swaps.append({"num": number, "new_url": link, "old_url": old_purchase})

    summary = {
        "dry_run": args.dry_run,
        "links_in_csv": len(links),
        "queue_updated": updated,
        "rearmed_for_card_creation": rearmed,
        "card_url_swaps_needed": card_swaps,
    }
    if not args.dry_run and updated:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        shutil.copy2(QUEUE_PATH, QUEUE_PATH.with_name(QUEUE_PATH.name + f".backup_before_affiliate_apply_{stamp}"))
        QUEUE_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
